name: calculator
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #connectivity_plus: ^latest_version
  #fluttertoast: ^latest_version
  connectivity_plus: ^2.3.3
  battery_plus: 6.0.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
